-- Native business schema; original UUIDs, token hashes and message order survive.
CREATE SCHEMA IF NOT EXISTS commerce;
CREATE TABLE IF NOT EXISTS commerce.accounts (
    id text PRIMARY KEY, username text NOT NULL, username_key text NOT NULL UNIQUE,
    display_name text NOT NULL, role text NOT NULL CHECK(role IN ('buyer','merchant')),
    password_hash text NOT NULL, created_at timestamptz NOT NULL,
    UNIQUE(id,role)
);
CREATE TABLE IF NOT EXISTS commerce.tokens (
    token_hash text PRIMARY KEY, account_id text NOT NULL REFERENCES commerce.accounts(id),
    created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS commerce.products (
    id text PRIMARY KEY, merchant_id text NOT NULL REFERENCES commerce.accounts(id),
    title text NOT NULL CHECK(length(btrim(title))>0), description text NOT NULL,
    sku_id text, provenance text NOT NULL CHECK(provenance='merchant_declared_unverified'),
    created_at timestamptz NOT NULL, catalog_status text NOT NULL DEFAULT 'available',
    catalog_label text NOT NULL DEFAULT '演示商品', display_price_cents bigint NOT NULL CHECK(display_price_cents>0),
    price_basis text NOT NULL DEFAULT 'not_provided', price_as_of text,
    category text NOT NULL DEFAULT '其他商品' CHECK(length(btrim(category))>0),
    merchant_role text NOT NULL DEFAULT 'merchant' CHECK(merchant_role='merchant'),
    FOREIGN KEY(merchant_id,merchant_role) REFERENCES commerce.accounts(id,role),
    UNIQUE(id,merchant_id)
);
CREATE TABLE IF NOT EXISTS commerce.catalog_assignments (
    sku_id text PRIMARY KEY, merchant_id text NOT NULL REFERENCES commerce.accounts(id),
    display_title text NOT NULL, catalog_status text NOT NULL,
    assignment_type text NOT NULL CHECK(assignment_type='simulated'),
    source_version text NOT NULL, created_at timestamptz NOT NULL, category text NOT NULL DEFAULT '其他商品'
);
CREATE TABLE IF NOT EXISTS commerce.demo_purchases (
    id text PRIMARY KEY, buyer_id text NOT NULL REFERENCES commerce.accounts(id), sku_id text NOT NULL,
    order_id text NOT NULL, merchant_id text NOT NULL REFERENCES commerce.accounts(id),
    order_alias text NOT NULL, fulfillment_status text NOT NULL, source_version text NOT NULL,
    created_at timestamptz NOT NULL,
    buyer_role text NOT NULL DEFAULT 'buyer' CHECK(buyer_role='buyer'),
    merchant_role text NOT NULL DEFAULT 'merchant' CHECK(merchant_role='merchant'),
    FOREIGN KEY(buyer_id,buyer_role) REFERENCES commerce.accounts(id,role),
    FOREIGN KEY(merchant_id,merchant_role) REFERENCES commerce.accounts(id,role),
    UNIQUE(buyer_id,order_id,sku_id), UNIQUE(id,buyer_id,merchant_id)
);
CREATE TABLE IF NOT EXISTS commerce.conversations (
    id text PRIMARY KEY, product_id text NOT NULL, buyer_id text NOT NULL,
    merchant_id text NOT NULL, status text NOT NULL CHECK(status IN ('open','closed')),
    created_at timestamptz NOT NULL,
    access_mode text NOT NULL DEFAULT 'ai_private' CHECK(access_mode IN ('ai_private','merchant_shared')),
    merchant_visible integer NOT NULL DEFAULT 0 CHECK(merchant_visible IN (0,1)),
    handoff_summary_json text NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(handoff_summary_json::jsonb)='object'),
    purchase_id text,
    handoff_state text NOT NULL DEFAULT 'ai_support'
        CHECK(handoff_state IN ('ai_support','awaiting_merchant','merchant_processing','merchant_replied','resolved')),
    buyer_role text NOT NULL DEFAULT 'buyer' CHECK(buyer_role='buyer'),
    merchant_role text NOT NULL DEFAULT 'merchant' CHECK(merchant_role='merchant'),
    FOREIGN KEY(product_id,merchant_id) REFERENCES commerce.products(id,merchant_id),
    FOREIGN KEY(buyer_id,buyer_role) REFERENCES commerce.accounts(id,role),
    FOREIGN KEY(merchant_id,merchant_role) REFERENCES commerce.accounts(id,role),
    FOREIGN KEY(purchase_id,buyer_id,merchant_id) REFERENCES commerce.demo_purchases(id,buyer_id,merchant_id)
);
CREATE TABLE IF NOT EXISTS commerce.messages (
    sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id text NOT NULL UNIQUE, conversation_id text NOT NULL REFERENCES commerce.conversations(id),
    sender_type text NOT NULL CHECK(sender_type IN ('buyer','merchant','ai')),
    sender_id text, content text NOT NULL, client_message_id text, reply_to_id text,
    metadata_json text NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(metadata_json::jsonb)='object'),
    created_at timestamptz NOT NULL,
    CHECK((sender_type='ai' AND sender_id IS NULL) OR (sender_type<>'ai' AND sender_id IS NOT NULL)),
    FOREIGN KEY(sender_id,sender_type) REFERENCES commerce.accounts(id,role),
    UNIQUE(conversation_id,id), UNIQUE(reply_to_id),
    FOREIGN KEY(conversation_id,reply_to_id) REFERENCES commerce.messages(conversation_id,id),
    UNIQUE(conversation_id,sender_id,client_message_id)
);
CREATE TABLE IF NOT EXISTS commerce.handoff_events (
    id text PRIMARY KEY, conversation_id text NOT NULL REFERENCES commerce.conversations(id),
    request_id text UNIQUE, state text NOT NULL, actor_id text REFERENCES commerce.accounts(id),
    summary_json text NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(summary_json::jsonb)='object'),
    created_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS commerce.message_feedback (
    message_id text NOT NULL REFERENCES commerce.messages(id),
    account_id text NOT NULL REFERENCES commerce.accounts(id),
    rating text NOT NULL CHECK(rating IN ('helpful','not_helpful','incorrect')),
    note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL, PRIMARY KEY(message_id,account_id)
);
CREATE INDEX IF NOT EXISTS idx_commerce_tokens_account ON commerce.tokens(account_id);
CREATE INDEX IF NOT EXISTS idx_commerce_tokens_expiry ON commerce.tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_commerce_products_merchant ON commerce.products(merchant_id);
CREATE INDEX IF NOT EXISTS idx_commerce_products_sku_merchant ON commerce.products(sku_id,merchant_id);
CREATE INDEX IF NOT EXISTS idx_commerce_conversations_buyer ON commerce.conversations(buyer_id,created_at);
CREATE INDEX IF NOT EXISTS idx_commerce_conversations_merchant ON commerce.conversations(merchant_id,merchant_visible,created_at);
CREATE INDEX IF NOT EXISTS idx_commerce_messages_conversation ON commerce.messages(conversation_id,sequence);
CREATE INDEX IF NOT EXISTS idx_commerce_purchases_buyer ON commerce.demo_purchases(buyer_id);
CREATE INDEX IF NOT EXISTS idx_commerce_assignments_merchant ON commerce.catalog_assignments(merchant_id);
CREATE TABLE IF NOT EXISTS commerce.migrations (
    migration_id text PRIMARY KEY, source_fingerprint text NOT NULL,
    backup_path text NOT NULL, verified_counts jsonb NOT NULL, verified_hashes jsonb NOT NULL,
    completed_at timestamptz NOT NULL DEFAULT now()
);
